weights: yolov7/lastepoch_model_batch16_epoch200.pt
cfg: yolov7/cfg/training/yolov7.yaml
data: data/monkey_cat_dog_asYolov7input/data.yaml
hyp: yolov7/data/hyp.scratch.custom.yaml
epochs: 50
batch_size: 12
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: PROJECT_output_mcd
entity: null
name: mcd_from_batch12_epoch200_50epochsmore
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
world_size: 1
global_rank: -1
save_dir: PROJECT_output_mcd/mcd_from_batch12_epoch200_50epochsmore
total_batch_size: 12
